name: Java Maven CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
          
      - name: Build & Run Tests
        run: mvn clean package -Dmaven.test.skip=true

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maven-build
          path: target/*.jar
          
  docker:
    name: Build & Push Docker Image
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: maven-build
          path: target/
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: docker build -t shalika199/my-github-java-app:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push shalika199/my-github-java-app:latest
          
  deploy:
    name: Deploy to Server
    needs: docker
    runs-on: ubuntu-latest
    environment: DEV
      
    steps:
      - name: SSH into Server & Deploy
        uses: appleboy/ssh-action@v0.1.7
        with: 
          name: maven-build
          path: target/
          script: |
            docker pull shalika199/my-github-java-app:latest
            docker stop my-github-java-app || true
            docker rm my-github-java-app || true
